### ISSUE TITLE
Accept weights that are not `AbstractVector{<:AbstractFloat}`

### ISSUE THREAD

**Issue by oxinabox** [JuliaStats/Lasso.jl#43]
In StatsBase 0.32.1  `uweights(n)::AbstractVector{Int}`.

That causes this to error

**Comment by birm** [comment]
I don't see a type restriction on weights placed by this repository. (https://github.com/JuliaStats/Lasso.jl/search?q=weights&unscoped_q=weights)
Also, I'm able to run your snippet without issue using StatsBase
```
julia> uweights(5)::AbstractVector{Int}
5-element UnitWeights{Int64}:
 1
 1
 1
 1
 1
```
Did I miss something? What code did you run to get an error? What was the error?

**Comment by oxinabox** [comment]
It may be coming in via a dependency, eg on GLM.

I don't have the code handy (or a new in the first place) will try and make one later.

**Comment by AsafManela** [comment]
Can we close this issue?
