### ISSUE TITLE
please tag a new release for Pkg resolver

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaStats/Lasso.jl#64]
Hi, this package is causing problems for me because it restricts Reexport to 0.2 in latest tag.  In master, this has been updated to version 1.

Could we please get a tag of this so that packages that depend on it can update properly?

**Comment by ExpandingMan** [comment]
This should wait for #63.

**Comment by juliohm** [comment]
This issue is also affecting our current project. Appreciate if you can tag the release. I don't understand how changing Reexport.jl from v0.2 to v1.0 can break any code. The release bump is just to signal stability as far as I know.
