### ISSUE TITLE
upgrades and documentation

### ISSUE THREAD

**Issue by kpmessier** [JuliaStats/Lasso.jl#66]
Are there plans to create CRAN glmnet-like features and documentation? 

Features that are helpful from glmnet: 

1. k-fold CV 
2. plotting - cv MSE and lambda plots (including degrees of freedom on the top x-axis too).

Thanks

**Comment by AsafManela** [comment]
Docs can certainly be improved. PRs welcome.

As for the features:
1. k-fold CV is supported. See example [here](https://juliastats.org/Lasso.jl/stable/lasso/#Lasso-model-fitting-1)
2. Plotting is provided by the [LassoPlot.jl](https://github.com/AsafManela/LassoPlot.jl) package
