### ISSUE TITLE
matrix is not square,how to fix it?

### ISSUE THREAD

**Issue by HajMehran1396** [JuliaStats/Lasso.jl#76]
age=sh["F2:F3778"]
sex=sh["D2:D3778"]
wage=sh["I2:I3778"]
work=sh["H2:H3778"]
family_size=sh["C2:C3778"]
data = (;age,sex,wage,work,family_size);
X=[ones(n) age sex family_size work]
beta = [:beta1,:beta2,:beta3,:beta4,:beta5,:beta6 ]
beta_ml=zeros(6,1)
xf = XLSX.readxlsx("HW1.xlsx")
n=3777
sh = xf["Sheet1"]
age=sh["F2:F3778"]
sex=sh["D2:D3778"]
wage=sh["I2:I3778"]
work=sh["H2:H3778"]
family_size=sh["C2:C3778"]
data = (;age,sex,wage,work,family_size);
X=[ones(n) age sex family_size work]
beta = [:beta1,:beta2,:beta3,:beta4,:beta5,:beta6 ]
beta_ml=zeros(6,1)
result=optimize(beta->sum(.-log(1/sqrt(2*π*beta[6]^2)) .+ 1/(2 * beta[6]^2) .* ((wage.-beta[5]*(beta[1]+beta[2]*age+beta[3]*sex+beta[4]*family_size).*work.^((beta[1]+beta[2]*age+beta[3]*sex+beta[4]*family_size).-1))./(beta[5])*(1
    .+(beta[1]+beta[2]*age+beta[3]*sex+beta[4]*family_size).*log(work)).*(work.^(beta[1]+beta[2]*age+beta[3]*sex+beta[4]*family_size).-1)).^2),[0.0,0.0,0.0,0.0,0.0,0.0])
beta_ml=Optim.minimizer(result)

**Comment by andreasnoack** [comment]
Please provide some more context for this problem and please also make the example self contained such that others can run it. Otherwise there is little chance that you'd receive any helpful replies here.

**Comment by andreasnoack** [comment]
I can see from the original message that this is actually from an exercise. Please don't post such questions in the issue tracker. Ask in class.
